#ifndef _LB_DESK_H_
#define _LB_DESK_H_

#include "hyTypes.h"
#include "grap_api.h"

#define  LB_MEM_IDX		1

/*用作预览的buf*/
#define LB_PREVIEW_BUF_NUM					4

#ifdef W818C
#define LB_DISPLAY_START_ROW				30
#define LB_DISPLAY_START_COL				30
#else
#define LB_DISPLAY_START_ROW				50
#define LB_DISPLAY_START_COL				0
#endif

#define LB_PREVIEW_DISPLAY_WIDTH			240
#define LB_PREVIEW_DISPLAY_HEIGHT			180
#define LB_PREVIEW_DISPLAY_BUFSIZE			(LB_PREVIEW_DISPLAY_WIDTH * LB_PREVIEW_DISPLAY_HEIGHT * 2)
#define LB_PREVIEW_DISPLAY_PIXELS			(LB_PREVIEW_DISPLAY_WIDTH * LB_PREVIEW_DISPLAY_HEIGHT)

#define LB_PREVIEW_320_240_WIDTH			320
#define LB_PREVIEW_320_240_HEIGHT			240
#define LB_PREVIEW_320_240_PIXELS			(LB_PREVIEW_320_240_WIDTH * LB_PREVIEW_320_240_HEIGHT)

#define LB_PREVIEW_640_480_WIDTH			640
#define LB_PREVIEW_640_480_HEIGHT			480
#define LB_PREVIEW_640_480_PIXELS			(LB_PREVIEW_640_480_WIDTH * LB_PREVIEW_640_480_HEIGHT)



//#define LB_QVGA_PREVIEW
#define LB_VGA_PREVIEW

#ifdef LB_VGA_PREVIEW
	#define LB_PREVIEW_H_SIZE			LB_PREVIEW_640_480_HEIGHT
	#define LB_PREVIEW_W_SIZE			LB_PREVIEW_640_480_WIDTH

	#define LB_PREVIEW_Y_SIZE			LB_PREVIEW_640_480_PIXELS
	#define LB_PREVIEW_U_SIZE			(LB_PREVIEW_640_480_PIXELS >> 2)
	#define LB_PREVIEW_V_SIZE			(LB_PREVIEW_640_480_PIXELS >> 2)
#elif defined LB_QVGA_PREVIEW
	#define LB_PREVIEW_H_SIZE			LB_PREVIEW_320_240_HEIGHT
	#define LB_PREVIEW_W_SIZE			LB_PREVIEW_320_240_WIDTH

	#define LB_PREVIEW_Y_SIZE			LB_PREVIEW_320_240_PIXELS
	#define LB_PREVIEW_U_SIZE			(LB_PREVIEW_320_240_PIXELS >> 2)
	#define LB_PREVIEW_V_SIZE			(LB_PREVIEW_320_240_PIXELS >> 2)
#endif


//#define LB_QVGA_RECOGNISE	//320*240 大小识别

#ifdef LB_QVGA_RECOGNISE
	#define LB_DECODE_DATA_H			LB_PREVIEW_320_240_HEIGHT
	#define LB_DECODE_DATA_W			LB_PREVIEW_320_240_WIDTH
#else
	#define LB_DECODE_DATA_H			LB_PREVIEW_640_480_HEIGHT
	#define LB_DECODE_DATA_W			LB_PREVIEW_640_480_WIDTH
#endif

typedef enum
{
	LB_STATE_INIT=0,	//初始化状态
	LB_STATE_GETOK,		//成功
	LB_STATE_UNKNOW,	//不能支持的类型
	LB_STATE_START,		//开始识别
	LB_STATE_QUIT		//退出

}eLBSTATE;



#endif //_LB_DESK_H_