#ifndef _QR_DESK_H_
#define _QR_DESK_H_

#include "hyTypes.h"
#include "grap_api.h"

#define  QR_MEM_IDX		1

/*用作预览的buf*/
#define QR_PREVIEW_BUF_NUM					4

#ifdef W818C
#define QR_DISPLAY_START_ROW				30
#define QR_DISPLAY_START_COL				30
#else
#define QR_DISPLAY_START_ROW				50
#define QR_DISPLAY_START_COL				0
#endif

#define QR_PREVIEW_DISPLAY_WIDTH			240
#define QR_PREVIEW_DISPLAY_HEIGHT			180
#define QR_PREVIEW_DISPLAY_BUFSIZE			(QR_PREVIEW_DISPLAY_WIDTH * QR_PREVIEW_DISPLAY_HEIGHT * 2)
#define QR_PREVIEW_DISPLAY_PIXELS			(QR_PREVIEW_DISPLAY_WIDTH * QR_PREVIEW_DISPLAY_HEIGHT)

#define QR_PREVIEW_320_240_WIDTH			320
#define QR_PREVIEW_320_240_HEIGHT			240
#define QR_PREVIEW_320_240_PIXELS			(QR_PREVIEW_320_240_WIDTH * QR_PREVIEW_320_240_HEIGHT)

#define QR_PREVIEW_640_480_WIDTH			640
#define QR_PREVIEW_640_480_HEIGHT			480
#define QR_PREVIEW_640_480_PIXELS			(QR_PREVIEW_640_480_WIDTH * QR_PREVIEW_640_480_HEIGHT)



//#define QR_QVGA_PREVIEW
#define QR_VGA_PREVIEW

#ifdef QR_VGA_PREVIEW
	#define QR_PREVIEW_H_SIZE			QR_PREVIEW_640_480_HEIGHT
	#define QR_PREVIEW_W_SIZE			QR_PREVIEW_640_480_WIDTH

	#define QR_PREVIEW_Y_SIZE			QR_PREVIEW_640_480_PIXELS
	#define QR_PREVIEW_U_SIZE			(QR_PREVIEW_640_480_PIXELS >> 2)
	#define QR_PREVIEW_V_SIZE			(QR_PREVIEW_640_480_PIXELS >> 2)
#elif defined QR_QVGA_PREVIEW
	#define QR_PREVIEW_H_SIZE			QR_PREVIEW_320_240_HEIGHT
	#define QR_PREVIEW_W_SIZE			QR_PREVIEW_320_240_WIDTH

	#define QR_PREVIEW_Y_SIZE			QR_PREVIEW_320_240_PIXELS
	#define QR_PREVIEW_U_SIZE			(QR_PREVIEW_320_240_PIXELS >> 2)
	#define QR_PREVIEW_V_SIZE			(QR_PREVIEW_320_240_PIXELS >> 2)
#endif


//#define QR_QVGA_RECOGNISE	//320*240 大小识别

#ifdef QR_QVGA_RECOGNISE
	#define QR_DECODE_DATA_H			QR_PREVIEW_320_240_HEIGHT
	#define QR_DECODE_DATA_W			QR_PREVIEW_320_240_WIDTH
#else
	#define QR_DECODE_DATA_H			QR_PREVIEW_640_480_HEIGHT
	#define QR_DECODE_DATA_W			QR_PREVIEW_640_480_WIDTH
#endif

typedef enum
{
	QR_STATE_INIT=0,	//初始化状态
	QR_STATE_GETOK,		//成功
	QR_STATE_UNKNOW,	//不能支持的类型
	QR_STATE_START,		//开始识别
	QR_STATE_QUIT		//退出

}eQRSTATE;



#endif //_QR_DESK_H_